# Main github repository to fetch from.
# This is going to be our base, into which we merge patches and pull requests.
repo = "helix-editor/helix"

# The main repository's branch.
remote-branch = "master"

# Branch which patchy will use to do all of its work on.
local-branch = "patchy"

# List of pull requests numbers which you would like to merge into the repository and branch you have specified previously.
pull-requests = [
  # Basic icon support.
  "12369",
  # :tree-sitter-tree
  "12207",
  # Color swatches.
  "12308",
  # Fullscreen pickers/overlays.
  "12311",
]

# Optional: A list of patches to apply
# patches = []
